const PERMISSION_CODE = {
  READ_PERMISSION: 1,
  CREATE_PERMISSION: 2,
  UPDATE_PERMISSION: 3,
  DELETE_PERMISSION: 4,
  READ_ROLE: 5,
  CREATE_ROLE: 6,
  UPDATE_ROLE: 7,
  DELETE_ROLE: 8,
  GRANT_PERMISSION: 9,
  REFUSE_PERMISSION: 10,
  READ_PROFILE: 11,
  CREATE_PROFILE: 12,
  UPDATE_PROFILE: 13,
  DELETE_PROFILE: 14,
  READ_USER: 15,
  CREATE_USER: 16,
  UPDATE_USER: 17,
  DELETE_USER: 18,
};

export { PERMISSION_CODE };
